#!/usr/bin/env node
// Builds the two files people paste into the Apps Script editor:
//   dist/BlackbaudToCalendar.gs  all of the tool's code (replace it to update)
//   dist/Settings.gs             the settings template (edit it once, keep it)
const fs = require('fs');
const path = require('path');
const FILES = require('./files');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'apps-script');
const DIST = path.join(ROOT, 'dist');

function read(file) {
  return fs.readFileSync(path.join(SRC, file), 'utf8');
}

function buildMain() {
  const header = [
    '// Blackbaud → Google Calendar (https://github.com/shrimpsooup2/BlauckBaud2Calendar)',
    '// Generated by scripts/build.js from apps-script/. Put your settings in Settings.gs, not here.',
    '',
  ].join('\n');
  return header + FILES.map((file) => `\n// ===== ${file} =====\n\n${read(file)}`).join('');
}

function buildSettings() {
  return read('Settings.js');
}

const OUTPUTS = {
  'BlackbaudToCalendar.gs': buildMain,
  'Settings.gs': buildSettings,
};

module.exports = { OUTPUTS, DIST };

if (require.main === module) {
  fs.mkdirSync(DIST, { recursive: true });
  for (const [name, build] of Object.entries(OUTPUTS)) {
    fs.writeFileSync(path.join(DIST, name), build());
    console.log(`wrote dist/${name}`);
  }
}
